from __future__ import annotations 

PERFORMANCE_VERSION = "V17_PERFORMANCE_EVALUATOR_1_OFFLINE_PASSIVE"

PERFORMANCE_ROLE = "EVALUATION_ONLY"
PERFORMANCE_IS_OFFICIAL_DECISION = False
PERFORMANCE_CAN_PUBLISH = False

RESULT_WON = "WON"
RESULT_LOST = "LOST"
RESULT_VOID = "VOID"
RESULT_PENDING = "PENDING"
RESULT_EXPIRED = "EXPIRED"
RESULT_CANCELLED = "CANCELLED"
RESULT_UNKNOWN = "UNKNOWN"

DECIDED_RESULTS = {RESULT_WON, RESULT_LOST}
NON_DECIDED_RESULTS = {
    RESULT_VOID,
    RESULT_PENDING,
    RESULT_EXPIRED,
    RESULT_CANCELLED,
    RESULT_UNKNOWN,
}

MARKET_OVER = "OVER"
MARKET_UNDER = "UNDER"
MARKET_NO_BET = "NO_BET"
MARKET_BLOCKED = "BLOCKED"
MARKET_UNKNOWN = "UNKNOWN"

DATA_QUALITY_UNKNOWN = "UNKNOWN"

MINUTE_BUCKETS = (
    "M00_15",
    "M16_30",
    "M31_45",
    "M46_60",
    "M61_75",
    "M76_90",
    "M90_PLUS",
    "UNKNOWN",
)

CONFIDENCE_BUCKETS = (
    "C00_39",
    "C40_49",
    "C50_59",
    "C60_69",
    "C70_79",
    "C80_89",
    "C90_100",
    "UNKNOWN",
)

DEFAULT_DB_PATH = "app/v17/storage/performance.db"
